<a href="https://colab.research.google.com/github/Twily-Spark/master1/blob/master/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install svg.py
!pip install svg.path

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import math
from time import time
import pandas as pd

from svg.path import parse_path
from svg.path.path import Line
from xml.dom import minidom


In [14]:
initPt=[[1,2,1,0],[0,1,2,1]]
initP_np=np.array(initPt)
rotA=lambda th: np.array([[math.cos(th), -math.sin(th)],[math.sin(th), math.cos(th)]])

ang1=0
ang2=math.pi

display(rotA(ang1))
display(rotA(ang2))

print(initP_np)
print('~~~~~~')
print(rotA(ang1).dot(initP_np))

array([[ 1., -0.],
       [ 0.,  1.]])

array([[-1.0000000e+00, -1.2246468e-16],
       [ 1.2246468e-16, -1.0000000e+00]])

[[1 2 1 0]
 [0 1 2 1]]
~~~~~~
[[1. 2. 1. 0.]
 [0. 1. 2. 1.]]
